import './globals.css';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
	title: 'Next JS Smart Cam',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang='en'>
			<body
				className={`${inter.className} flex flex-col items-center justify-between p-24`}
			>
				<div className='bg-blue-950 p-8 mb-12'>
					This is part of the RootLayout
				</div>
				{children}
			</body>
		</html>
	);
}
