import Link from 'next/link';

export const metadata = {
	title: 'Dynamic Page',
	description: 'Generated by create next app',
};

interface PageProps {
	params: {
		id: string;
	};
}

function Page({ params: { id } }: PageProps) {
	return (
		<div className=''>
			Dynamic page param:{' '}
			<span className='text-xl font-bold text-sky-500'>{id}</span>
			<Link href={'/'} className='block text-center'>
				<button className='mt-8 px-8 py-4 bg-sky-900 rounded-xl'>
					Main Page
				</button>
			</Link>
		</div>
	);
}

export default Page;
